name: golangci-lint
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "10.0"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest