name: golangci-lint
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "10.0"

      - name: Symlink libclang.so (Linux)
        if: contains(matrix.os, 'ubuntu')
        run: sudo ln -s libclang-11.so.1 /lib/x86_64-linux-gnu/libclang.so
        working-directory: ${{ env.LLVM_PATH }}/lib

      - name: Set up Clang as C and C++ compiler
        run: |
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest